### ISSUE TITLE
Character spacing

### ISSUE THREAD

**Issue by SchoolyB** [bbland1/is-shoujo-quiz#47]
Very minor problem with the spacing of your hyperlinks shown in the picture below. This is a screenshot from a Samsung A53 cropped only to focus in on the para where I found the issue. 
![Screenshot_20240105_165331_Brave.jpg](https://github.com/bbland1/is-shoujo-quiz/assets/110133622/acb03bdf-303a-4ff4-a417-e3d6be271b19)

**Comment by bbland1** [comment]
This is a good reminder to proof read 😅 because I definitely found a few more spots the same issue lol
